import type { Trip } from '../types';
import { generateId } from './storage';

export function createSampleTrip(): Trip {
  const now = Date.now();
  return {
    id: generateId(),
    name: '曼谷周末逃跑计划',
    destination: '曼谷',
    startDate: '2026-04-03',
    endDate: '2026-04-06',
    coverColor: '#F97316',
    baseCurrency: 'CNY',
    createdAt: now,
    updatedAt: now,
    days: [
      // 4月3日（周五）· 出发日
      {
        id: generateId(),
        date: '2026-04-03',
        activities: [
          {
            id: generateId(),
            title: 'CA979 北京→曼谷',
            category: 'flight',
            startTime: '20:00',
            location: '北京首都国际机场',
            notes: '提前填好在线入境卡',
            order: 0,
          },
        ],
      },
      // 4月4日（周六）· Day 1
      {
        id: generateId(),
        date: '2026-04-04',
        activities: [
          {
            id: generateId(),
            title: 'MUU Bangkok Hotel 入住',
            category: 'hotel',
            startTime: '01:00',
            location: 'Thonglor',
            notes: 'SLH精品酒店；接机，直接入住休息',
            order: 0,
          },
          {
            id: generateId(),
            title: '酒店早餐',
            category: 'dining',
            startTime: '08:30',
            location: 'MUU Bangkok Hotel',
            notes: '周末截止至13:00，不用急',
            order: 1,
          },
          {
            id: generateId(),
            title: '四面佛 Erawan Shrine',
            category: 'sightseeing',
            startTime: '10:00',
            endTime: '10:45',
            location: 'BTS Chit Lom',
            notes: 'BTS Chit Lom 下车步行；花环约200铢，顺时针拜四面',
            expense: { amount: 200, currency: 'THB' },
            order: 2,
          },
          {
            id: generateId(),
            title: '逛 EmSphere',
            category: 'shopping',
            startTime: '10:45',
            endTime: '13:30',
            location: 'BTS Phrom Phong',
            notes: '逛 Alo / Lululemon / 超市等；A Keen House在G层',
            order: 3,
          },
          {
            id: generateId(),
            title: 'Nara / EmSphere Pad Thai',
            category: 'dining',
            startTime: '13:30',
            endTime: '14:00',
            location: 'EmSphere 楼下',
            notes: '视饿不饿决定',
            order: 4,
          },
          {
            id: generateId(),
            title: 'Cum Coffee',
            category: 'cafe',
            startTime: '14:00',
            endTime: '15:00',
            location: 'EmSphere 附近',
            order: 5,
          },
          {
            id: generateId(),
            title: 'Klover Massages',
            category: 'massage',
            startTime: '15:00',
            endTime: '17:00',
            location: 'Chong Nonsi',
            notes: 'Grab 约20分钟；下午1点开门，提前预约',
            order: 6,
          },
          {
            id: generateId(),
            title: 'Jae Keang 泰餐',
            category: 'dining',
            startTime: '17:00',
            endTime: '18:30',
            location: 'BTS National Stadium',
            notes: 'Grab 约15分钟；地道泰餐',
            order: 7,
          },
          {
            id: generateId(),
            title: '朱拉隆功夜市',
            category: 'shopping',
            startTime: '18:30',
            endTime: '20:00',
            location: '朱拉隆功大学附近',
            notes: '随便逛逛',
            order: 8,
          },
          {
            id: generateId(),
            title: 'Yao Rooftop Bar',
            category: 'bar',
            startTime: '20:00',
            endTime: '22:00',
            location: 'Yao Rooftop',
            notes: 'Grab 前往',
            order: 9,
          },
          {
            id: generateId(),
            title: 'Banana Room',
            category: 'entertainment',
            startTime: '22:00',
            location: 'Banana Room',
            notes: 'Grab 前往；看表演、看人',
            order: 10,
          },
        ],
      },
      // 4月5日（周日）· Day 2
      {
        id: generateId(),
        date: '2026-04-05',
        activities: [
          {
            id: generateId(),
            title: '酒店早餐 + 泳池',
            category: 'hotel',
            startTime: '09:30',
            endTime: '12:00',
            location: 'MUU Bangkok Hotel',
            notes: '周日截止至13:00；泳池随意泡',
            order: 0,
          },
          {
            id: generateId(),
            title: 'Check-out 退房',
            category: 'hotel',
            startTime: '12:00',
            location: 'MUU Bangkok Hotel',
            notes: '寄存行李',
            order: 1,
          },
          {
            id: generateId(),
            title: 'Brunch / 打抛饭',
            category: 'dining',
            startTime: '12:30',
            endTime: '14:00',
            location: 'Thonglor 附近',
            notes: '随便找',
            order: 2,
          },
          {
            id: generateId(),
            title: 'So Thai Spa',
            category: 'massage',
            startTime: '14:00',
            endTime: '15:45',
            location: 'Surawong Rd, Silom',
            notes: '4.9分；WhatsApp提前订位；90分钟传统泰式',
            order: 3,
          },
          {
            id: generateId(),
            title: '前往 Sathorn Pier',
            category: 'car',
            startTime: '15:45',
            endTime: '16:00',
            location: 'Sathorn Pier',
            notes: 'Grab 约5分钟（2km，别走路）',
            order: 4,
          },
          {
            id: generateId(),
            title: '昭披耶河游船',
            category: 'boat',
            startTime: '16:00',
            endTime: '17:00',
            location: 'Chao Phraya Express Boat',
            notes: '欣赏大皇宫、黎明寺河景',
            order: 5,
          },
          {
            id: generateId(),
            title: '唐人街 Song Wat 街区',
            category: 'sightseeing',
            startTime: '17:00',
            endTime: '18:00',
            location: 'Ratchawong Pier → Song Wat',
            notes: '步行逛逛',
            order: 6,
          },
          {
            id: generateId(),
            title: '榴莲 + 唐人街小吃',
            category: 'dining',
            startTime: '18:00',
            endTime: '19:00',
            location: '唐人街',
            order: 7,
          },
          {
            id: generateId(),
            title: 'Fikeaw Yaowarat 海鲜烧烤',
            category: 'dining',
            startTime: '19:00',
            endTime: '21:00',
            location: '唐人街 Yaowarat',
            notes: '木炭明火烤龙虾；周日营业',
            order: 8,
          },
          {
            id: generateId(),
            title: 'Dry Wave Cocktail Studio',
            category: 'bar',
            startTime: '21:00',
            endTime: '23:00',
            location: 'Dry Wave Cocktail Studio',
            notes: "Asia's 50 Best #5；步行可达酒店；提前订位",
            order: 9,
          },
          {
            id: generateId(),
            title: '回酒店取行李',
            category: 'other',
            startTime: '23:00',
            endTime: '23:30',
            location: 'MUU Bangkok Hotel',
            notes: 'Grab 返回 MUU Thonglor',
            order: 10,
          },
          {
            id: generateId(),
            title: '前往素万那普机场',
            category: 'car',
            startTime: '23:30',
            location: '素万那普国际机场',
            notes: 'Grab 约30分钟（Thonglor更近机场！）',
            order: 11,
          },
        ],
      },
      // 4月6日（周一）· 返程
      {
        id: generateId(),
        date: '2026-04-06',
        activities: [
          {
            id: generateId(),
            title: 'ZH306 曼谷→深圳',
            category: 'flight',
            startTime: '03:00',
            location: '素万那普国际机场',
            order: 0,
          },
        ],
      },
    ],
  };
}
