import type { Trip } from '../types';
import { generateId } from './storage';

export function createSampleTrip(): Trip {
  const now = Date.now();
  return {
    id: generateId(),
    name: 'Welcome to BKK',
    destination: 'Bangkok',
    startDate: '2026-04-03',
    endDate: '2026-04-06',
    coverColor: '#F97316',
    baseCurrency: 'CNY',
    createdAt: now,
    updatedAt: now,
    days: [
      // Day 1 · 4月3日（周五）· 出发日 · 2项
      {
        id: generateId(),
        date: '2026-04-03',
        activities: [
          {
            id: generateId(),
            title: 'CA979 北京→曼谷',
            category: 'flight',
            startTime: '20:00',
            location: '北京首都国际机场',
            notes: '提前填好在线入境卡',
            order: 0,
          },
          {
            id: generateId(),
            title: '接机',
            category: 'other',
            startTime: '23:59',
            location: '素万那普机场',
            expense: { amount: 127, currency: 'CNY' },
            order: 1,
          },
        ],
      },
      // Day 2 · 4月4日（周六）· 11项
      {
        id: generateId(),
        date: '2026-04-04',
        activities: [
          {
            id: generateId(),
            title: 'MUU Bangkok Hotel 入住',
            category: 'hotel',
            startTime: '01:30',
            location: 'Thonglor',
            notes: '酒店联通的商业体有24小时的超市（Foodland）',
            expense: { amount: 6783, currency: 'THB' },
            order: 0,
          },
          {
            id: generateId(),
            title: '酒店早餐',
            category: 'dining',
            startTime: '08:30',
            location: 'MUU Bangkok Hotel',
            notes: '周末截止至13:00，不用急',
            order: 1,
          },
          {
            id: generateId(),
            title: 'Erawan Shrine 四面佛',
            category: 'sightseeing',
            startTime: '10:00',
            order: 2,
          },
          {
            id: generateId(),
            title: 'Songwat区，唐人街观光',
            category: 'sightseeing',
            startTime: '11:15',
            endTime: '13:00',
            notes: 'BTS Chit Lom / Siam 上车 到 Siam 换线 → MRT Blue Line 坐到：🔴 Wat Mangkon Station👉下车就是唐人街核心区',
            order: 3,
          },
          {
            id: generateId(),
            title: '午餐 Hansa River House/NAM 1068',
            category: 'dining',
            startTime: '13:00',
            order: 4,
          },
          {
            id: generateId(),
            title: '去Ratchawong Pier 坐船去 Sathorn Pier',
            category: 'boat',
            startTime: '14:00',
            endTime: '14:30',
            order: 5,
          },
          {
            id: generateId(),
            title: 'Sathorn 打车去 Klover',
            category: 'car',
            startTime: '14:30',
            endTime: '15:00',
            order: 6,
          },
          {
            id: generateId(),
            title: 'Klover Massages',
            category: 'massage',
            startTime: '15:00',
            endTime: '17:00',
            location: 'Chong Nonsi',
            notes: 'Grab 约20分钟；下午1点开门，提前预约 Thiw',
            order: 7,
          },
          {
            id: generateId(),
            title: 'Jae Keang 泰餐',
            category: 'dining',
            startTime: '17:00',
            endTime: '18:30',
            location: 'BTS National Stadium',
            notes: 'Grab 约15分钟；地道泰餐',
            order: 8,
          },
          {
            id: generateId(),
            title: '朱拉隆功夜市',
            category: 'shopping',
            startTime: '18:30',
            endTime: '20:00',
            location: '朱拉隆功大学附近',
            notes: '随便逛逛 吃点摊潭',
            order: 9,
          },
          {
            id: generateId(),
            title: 'Yao Rooftop Bar',
            category: 'bar',
            startTime: '20:00',
            endTime: '22:00',
            location: 'Yao Rooftop',
            notes: 'Grab 前往；已预约 Eddie Li',
            order: 10,
          },
        ],
      },
      // Day 3 · 4月5日（周日）· 7项
      {
        id: generateId(),
        date: '2026-04-05',
        activities: [
          {
            id: generateId(),
            title: '酒店早餐 + 泳池 + 运动',
            category: 'hotel',
            startTime: '09:30',
            endTime: '12:00',
            location: 'MUU Bangkok Hotel',
            notes: '周日截止至13:00',
            order: 0,
          },
          {
            id: generateId(),
            title: 'Check-out 退房',
            category: 'hotel',
            startTime: '12:00',
            location: 'MUU Bangkok Hotel',
            notes: '寄存行李',
            order: 1,
          },
          {
            id: generateId(),
            title: 'Cum Coffee',
            category: 'cafe',
            startTime: '12:30',
            endTime: '13:00',
            notes: '酒店出门即可',
            order: 2,
          },
          {
            id: generateId(),
            title: '逛Emsphere',
            category: 'shopping',
            startTime: '13:00',
            endTime: '15:00',
            notes: '逛 Alo / Lululemon 等；A Keen House在G层',
            order: 3,
          },
          {
            id: generateId(),
            title: 'Dry Wave Cocktail Studio',
            category: 'bar',
            startTime: '20:00',
            endTime: '23:00',
            location: 'Dry Wave Cocktail Studio',
            notes: "Asia's 50 Best #5；步行可达酒店；已预约的 eddie li",
            order: 4,
          },
          {
            id: generateId(),
            title: '回酒店取行李',
            category: 'other',
            startTime: '23:00',
            endTime: '23:30',
            location: 'MUU Bangkok Hotel',
            notes: 'Grab 返回 MUU Thonglor',
            order: 5,
          },
          {
            id: generateId(),
            title: '前往素万那普机场',
            category: 'car',
            startTime: '23:30',
            location: '素万那普国际机场',
            notes: 'Grab 约30分钟（Thonglor更近机场！）',
            order: 6,
          },
        ],
      },
      // Day 4 · 4月6日（周一）· 返程 · 1项
      {
        id: generateId(),
        date: '2026-04-06',
        activities: [
          {
            id: generateId(),
            title: 'ZH306 曼谷→深圳',
            category: 'flight',
            startTime: '03:00',
            location: '素万那普国际机场',
            order: 0,
          },
        ],
      },
    ],
  };
}
